name: build ios
run-name: ${{ github.actor }} is build ios
on:
  push:
    branches: [ main ]

jobs:
  build-dotnet:
   runs-on: ubuntu-latest
   steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 设置.net & sdk
        uses: subosito/flutter-action@v2
        with:
          dotnet-version: 8.0.x
          cache: true

      - name: 还原依赖并发布
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish ChatServer.csproj -c Release -o ./publish --self-contained false
      - name: SSH部署到服务器
        uses: actions/upload-artifact@v4
        with:
          name:  webapi-${{ matrix.dotnet-version }}-${{ matrix.os }}
          path: ./publish-${{ matrix.dotnet-version }}-${{ matrix.os }}

