name: build ios
run-name: ${{ github.actor }} is build ios
on:
  push:
    branches: [ main ]

jobs:
  build-android:
   runs-on: ubuntu-latest
   steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 安装 Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'

      - name: 配置国内镜像源（国内用户）
        run: |
          echo "PUB_HOSTED_URL=https://pub.flutter-io.cn" >> $GITHUB_ENV
          echo "FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn" >> $GITHUB_ENV
      - name: 安装 Flutter 依赖
        run:  flutter pub get
      - name: 构建 APK
        run: flutter build apk --release
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

